'use client'

import { useEffect, useState } from 'react'
import {
  Activity, ArrowRight, BrainCircuit, Check, ChevronRight, CircleAlert, Cloud, Code2,
  Eye, Fingerprint, Globe2, LockKeyhole, Menu, MousePointer2, Network, Play, Radar,
  Redo2, ShieldCheck, SlidersHorizontal, Terminal, X, Zap
} from 'lucide-react'

type PageKey = 'Overview' | 'Live Agent' | 'Privacy Firewall' | 'Perception' | 'Action Guard' | 'Benchmarks' | 'Activity Logs' | 'Settings'
type RunState = 'idle' | 'running' | 'complete'

const nav: { label: PageKey; icon: typeof Eye }[] = [
  { label: 'Overview', icon: Radar }, { label: 'Live Agent', icon: Activity }, { label: 'Privacy Firewall', icon: ShieldCheck },
  { label: 'Perception', icon: Eye }, { label: 'Action Guard', icon: LockKeyhole }, { label: 'Benchmarks', icon: Zap },
  { label: 'Activity Logs', icon: Terminal }, { label: 'Settings', icon: SlidersHorizontal },
]
const stages = [
  ['BROWSER', 'Raw screen stays local', Globe2], ['LOCAL VISION', 'Page structure detected', Eye], ['PII DETECTOR', 'Sensitive context identified', Fingerprint],
  ['PRIVACY FIREWALL', 'Redaction policy applied', ShieldCheck], ['MINIMUM DISCLOSURE', 'Sanitized context only', Network], ['CLOUD REASONING', 'Structured decision returned', BrainCircuit],
  ['ACTION GUARD', 'Action validated locally', LockKeyhole], ['BROWSER ACTION', 'Approved action executed', MousePointer2],
] as const
const demoSteps = ['Capture browser viewport', 'Run local perception', 'Detect sensitive fields', 'Apply privacy policy', 'Send minimum disclosure', 'Receive structured action', 'Validate action locally', 'Execute in browser']

function Status({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'amber' | 'red' | 'cyan' }) {
  return <span className={`status status-${tone}`}><span className="status-dot" />{children}</span>
}
function Panel({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section> }
function SectionTitle({ eyebrow, title, detail }: { eyebrow: string; title: string; detail?: string }) {
  return <div className="section-title"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{detail && <span className="muted small">{detail}</span>}</div>
}
function Metric({ label, value, note, tone = 'cyan' }: { label: string; value: string; note: string; tone?: string }) {
  return <div className={`metric metric-${tone}`}><span className="metric-label">{label}</span><strong>{value}</strong><span className="muted small">{note}</span></div>
}
function BrowserMock({ running }: { running: boolean }) {
  return <div className="browser-mock"><div className="browser-bar"><span className="window-dots"><i /><i /><i /></span><div className="address"><LockKeyhole size={11} /> checkout.example.test/account</div><Status tone={running ? 'cyan' : 'green'}>{running ? 'LOCAL SCAN' : 'LOCAL'}</Status></div><div className="browser-body"><div className="browser-brand"><div className="brand-mark small-mark">LG</div><span>example.test</span><span className="muted">Support</span><span className="muted">Account</span></div><div className="browser-content"><div className="fake-copy"><span className="skeleton w-60" /><span className="skeleton w-90" /><span className="skeleton w-42" /></div><div className="sensitive-card"><div><span className="tiny-label">ACCOUNT HOLDER</span><strong>Priya Sharma</strong></div><div><span className="tiny-label">EMAIL ADDRESS</span><strong>priya.sharma@example.test</strong></div><div className="redact-line"><span className="tiny-label">PAYMENT TOKEN</span><strong>•••• •••• •••• 4242</strong><span className="redacted">LOCAL ONLY</span></div></div><div className="browser-actions"><button className="ghost-button">Cancel</button><button className="primary-button">Continue <ArrowRight size={14} /></button></div></div><div className="scan-overlay"><div className="scan-tag"><Radar size={13} /> LOCAL PERCEPTION ACTIVE</div><span className="scan-corner top-left" /><span className="scan-corner top-right" /><span className="scan-corner bottom-left" /><span className="scan-corner bottom-right" /></div></div></div>
}
function Overview({ runState, runDemo }: { runState: RunState; runDemo: () => void }) {
  const active = runState === 'running' ? 4 : runState === 'complete' ? 8 : 0
  return <div className="page-content">
    <div className="hero"><div><div className="eyebrow"><span className="pulse" /> PRIVACY-PRESERVING BROWSER AGENT</div><h1>Reason in the cloud.<br /><span>Protect locally.</span></h1><p className="hero-copy">LocalGuard keeps raw browser perception and sensitive context on-device. The cloud receives only the minimum necessary disclosure, and every returned action is validated before execution.</p><div className="hero-actions"><button className="primary-button large" onClick={runDemo} disabled={runState === 'running'}><Play size={15} /> {runState === 'running' ? 'DEMO RUNNING' : runState === 'complete' ? 'RUN AGAIN' : 'RUN LIVE DEMO'}</button><span className="muted small"><span className="kbd">⌘</span> deterministic presentation flow</span></div></div><div className="hero-aside"><div className="aside-label">SYSTEM POSTURE</div><Status>LOCAL ENGINE READY</Status><div className="posture-row"><span>Raw screen crossing boundary</span><strong>0 bytes</strong></div><div className="posture-row"><span>Cloud connection</span><strong className="cyan-text">SANITIZED ONLY</strong></div><div className="posture-row"><span>Action policy</span><strong>ENFORCED</strong></div></div></div>
    <Panel className="pipeline-panel"><div className="pipeline-head"><div><div className="eyebrow">SIGNATURE ARCHITECTURE</div><h3>Observe → protect → disclose → act</h3></div><span className="demo-badge">DEMO FLOW</span></div><div className="pipeline">{stages.map(([name, desc, Icon], index) => <div className={`pipeline-step ${active > index ? 'step-done' : ''} ${active === index + 1 ? 'step-active' : ''}`} key={name}><div className="step-icon"><Icon size={16} /></div><div><strong>{name}</strong><span>{desc}</span></div>{index < stages.length - 1 && <ChevronRight className="step-arrow" size={15} />}</div>)}</div><div className="boundary-callout"><span className="boundary-line" /><span>RAW SCREEN NEVER CROSSES THIS BOUNDARY</span><span className="boundary-line" /></div><div className="pipeline-foot"><span><Check size={14} /> {runState === 'complete' ? 'Demo completed: browser action approved' : 'Sanitized context only reaches cloud reasoning'}</span><span className="muted small">SIMULATED RESULT — not runtime telemetry</span></div></Panel>
    <div className="overview-grid"><div><SectionTitle eyebrow="01 / PRIVACY BOUNDARY" title="What exists locally" detail="The screen is observed before disclosure" /><div className="boundary-grid"><BrowserMock running={runState === 'running'} /><Panel className="transform-panel"><div className="eyebrow">PRIVACY IMPACT</div><h3>Raw context → minimum disclosure</h3><div className="transform-row raw"><span className="transform-icon"><X size={15} /></span><div><strong>Raw browser screen</strong><span>Names, email, payment context</span></div><span className="blocked-label">BLOCKED</span></div><div className="transform-arrow"><ArrowRight size={16} /></div><div className="transform-row safe"><span className="transform-icon"><Check size={15} /></span><div><strong>Sanitized task context</strong><span>“Complete account checkout”</span></div><span className="allowed-label">ALLOWED</span></div><div className="transform-note"><ShieldCheck size={14} /><span>PII detection and redaction happen before network disclosure.</span></div></Panel></div></div><div><SectionTitle eyebrow="02 / DISCLOSURE" title="What the cloud sees" detail="Structured metadata, never raw pixels" /><Panel className="cloud-panel"><div className="cloud-header"><div className="cloud-icon"><Cloud size={18} /></div><div><strong>Cloud reasoning request</strong><span className="muted small">POST /reason · sanitized payload</span></div><Status tone="cyan">MINIMUM DISCLOSURE</Status></div><pre>{`{\n  "task": "complete_account_checkout",\n  "page": "account_checkout",\n  "visible_controls": ["cancel", "continue"],\n  "sensitive_fields": "redacted",\n  "raw_pixels": "not_included"\n}`}</pre><div className="cloud-response"><span className="tiny-label">STRUCTURED ACTION RETURNED</span><strong><MousePointer2 size={14} /> click("continue")</strong><span className="muted small">Awaiting local Action Guard validation</span></div></Panel><SectionTitle eyebrow="03 / ENFORCEMENT" title="Why the action is allowed" /><Panel className="guard-summary"><div className="guard-check"><ShieldCheck size={22} /><div><strong>Action Guard: approved</strong><span>Target is visible and policy-compliant</span></div><Status>ALLOWED</Status></div><div className="guard-rules"><span>Target exists</span><span>Action is reversible</span><span>No sensitive value exposed</span></div></Panel></div></div>
    <SectionTitle eyebrow="04 / HONEST TELEMETRY" title="Measured only when connected" detail="Demo values are explicitly labeled" /><div className="metrics-row"><Metric label="PII crossing boundary" value="0 bytes" note="DEMO POLICY ASSERTION" /><Metric label="Raw pixels disclosed" value="0" note="DEMO POLICY ASSERTION" tone="green" /><Metric label="Runtime latency" value="NOT MEASURED" note="WAITING FOR RUNTIME DATA" tone="amber" /><Metric label="Model confidence" value="NOT MEASURED" note="WAITING FOR RUNTIME DATA" tone="amber" /></div>
    <Panel className="comparison"><div><div className="eyebrow">ARCHITECTURE COMPARISON</div><h3>Traditional cloud agent vs LocalGuard</h3></div><div className="compare-table"><div className="compare-header"><span>DATA PATH</span><span>TRADITIONAL CLOUD AGENT</span><span>LOCALGUARD</span></div>{[['Raw browser perception','Sent to cloud','Stays on device'],['Sensitive context','Cloud-side filtering','Detected locally'],['Action execution','Cloud-directed','Validated locally'],['Policy enforcement','Distributed / unclear','Local Action Guard']].map(([a,b,c]) => <div className="compare-row" key={a}><span>{a}</span><span className="muted"><X size={13} /> {b}</span><span className="green-text"><Check size={13} /> {c}</span></div>)}</div></Panel>
  </div>
}
function DataPage({ page }: { page: PageKey }) {
  const title: Record<PageKey, string> = { 'Live Agent': 'Live Agent Workspace', 'Privacy Firewall': 'Privacy Firewall', Perception: 'Local Perception', 'Action Guard': 'Action Guard', Benchmarks: 'Benchmarks', 'Activity Logs': 'Activity Logs', Settings: 'System Settings', Overview: 'Overview' }
  return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">LOCALGUARD / {page.toUpperCase()}</div><h1>{title[page]}</h1><p className="muted">Inspect the local boundary, policy decisions, and structured agent state.</p></div><Status>{page === 'Benchmarks' ? 'NO RUNTIME DATA' : 'SYSTEM READY'}</Status></div>{page === 'Live Agent' ? <LiveWorkspace /> : page === 'Privacy Firewall' ? <Firewall /> : page === 'Action Guard' ? <ActionGuard /> : page === 'Perception' ? <Perception /> : page === 'Benchmarks' ? <Benchmarks /> : page === 'Activity Logs' ? <Logs /> : <Settings />}</div>
}
function LiveWorkspace() { return <div className="workspace"><Panel><SectionTitle eyebrow="LOCAL VIEWPORT" title="Browser observation" /><BrowserMock running /><div className="workspace-footer"><Status>OBSERVING LOCALLY</Status><span className="muted small">Raw pixels remain in this process</span></div></Panel><Panel><SectionTitle eyebrow="AGENT STATE" title="Decision trace" /><div className="trace-list">{demoSteps.slice(0, 6).map((s,i) => <div className="trace-item" key={s}><span className="trace-number">0{i+1}</span><div><strong>{s}</strong><span className="muted small">{i < 3 ? 'completed locally' : 'sanitized representation'}</span></div><Check size={14} className="green-text" /></div>)}</div><div className="notice"><CircleAlert size={15} /><span>Private model reasoning is not displayed. Only structured task metadata is shown.</span></div></Panel><Panel><SectionTitle eyebrow="CLOUD PAYLOAD" title="Sanitized context" /><div className="payload-code"><span className="code-key">task</span>: <span className="code-value">complete_account_checkout</span><br /><span className="code-key">page</span>: <span className="code-value">account_checkout</span><br /><span className="code-key">sensitive_fields</span>: <span className="code-redacted">[REDACTED]</span><br /><span className="code-key">raw_pixels</span>: <span className="code-redacted">not_included</span></div><div className="payload-stamp"><Network size={14} /> Minimum necessary disclosure</div></Panel></div> }
function Firewall() { return <><div className="filter-row"><button className="filter active">ALL <b>04</b></button><button className="filter">REDACTED <b>02</b></button><button className="filter">ALLOWED <b>02</b></button><span className="muted small">Policy version: LG-PRIVACY-01</span></div><Panel className="table-panel"><table><thead><tr><th>ELEMENT</th><th>CLASSIFICATION</th><th>DECISION</th><th>REASON</th></tr></thead><tbody>{[['Account holder','PERSONAL_DATA','REDACTED','Minimum disclosure'],['Email address','CONTACT_DATA','REDACTED','Minimum disclosure'],['Continue control','UI_CONTROL','ALLOWED','Required for task'],['Page title','PUBLIC_CONTEXT','ALLOWED','Non-sensitive']].map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td><span className="tag">{r[1]}</span></td><td><Status tone={r[2] === 'REDACTED' ? 'red' : 'green'}>{r[2]}</Status></td><td className="muted">{r[3]}</td></tr>)}</tbody></table></Panel><div className="empty-state"><ShieldCheck size={24} /><strong>Privacy firewall is enforcing locally</strong><span className="muted small">Every outbound context item is classified before disclosure.</span></div></> }
function Perception() { return <div className="perception-grid"><Panel><SectionTitle eyebrow="LOCAL VISION" title="Detected page structure" /><BrowserMock running /><div className="perception-tags"><span>FORM / 01</span><span>TEXT / 08</span><span>BUTTON / 02</span><span className="red-tag">PII / 03</span></div></Panel><Panel><SectionTitle eyebrow="DETECTION OUTPUT" title="Element map" /><div className="element-list">{['Account holder · PERSONAL_DATA','Email address · CONTACT_DATA','Payment token · FINANCIAL_DATA','Continue · UI_CONTROL','Cancel · UI_CONTROL'].map((x,i)=><div className="element-row" key={x}><span className={`element-dot ${i < 3 ? 'red-dot' : 'green-dot'}`} /><strong>{x.split(' · ')[0]}</strong><span className="muted small">{x.split(' · ')[1]}</span><ChevronRight size={14} /></div>)}</div><div className="notice green-notice"><Eye size={15} /><span>Perception is local. No image upload is required for this view.</span></div></Panel></div> }
function ActionGuard() { return <><div className="guard-hero"><div className="big-guard-icon"><ShieldCheck size={34} /></div><div><div className="eyebrow">LOCAL POLICY ENFORCEMENT</div><h2>Action Guard validates before execution.</h2><p className="muted">Cloud output is treated as a request, never as permission. The local guard checks target, scope, reversibility, and sensitive data exposure.</p></div></div><div className="action-grid"><Panel><div className="eyebrow">APPROVED ACTION</div><h3><MousePointer2 size={17} /> click(&quot;continue&quot;)</h3><div className="rule-checks">{['Target exists in current viewport','Target matches requested task','No sensitive value in payload','Action is within policy scope'].map(x=><div key={x}><Check size={14} />{x}</div>)}</div><Status>ALLOWED · EXECUTION READY</Status></Panel><Panel className="blocked-panel"><div className="eyebrow red-text">BLOCKED EXAMPLE</div><h3><CircleAlert size={17} /> type(&quot;•••• 4242&quot;)</h3><div className="rule-checks">{['Sensitive value detected','Action attempts PII input','Policy requires local handling'].map(x=><div key={x}><X size={14} />{x}</div>)}</div><Status tone="red">BLOCKED · SENSITIVE INPUT</Status></Panel></div></> }
function Benchmarks() { return <><div className="benchmark-note"><CircleAlert size={16} /><span>Benchmark data is not connected. The interface intentionally avoids fabricated latency, accuracy, or resource measurements.</span></div><div className="metrics-row"><Metric label="End-to-end latency" value="NOT MEASURED" note="WAITING FOR RUNTIME DATA" tone="amber" /><Metric label="PII precision / recall" value="NOT MEASURED" note="NO EVALUATION SET" tone="amber" /><Metric label="CPU / RAM / GPU" value="NOT MEASURED" note="NO RUNTIME TELEMETRY" tone="amber" /></div><Panel className="empty-large"><Zap size={26} /><h3>No benchmark runs recorded</h3><p className="muted">Connect a runtime measurement source to populate this view. Demo flows are not benchmark results.</p></Panel></> }
function Logs() { return <Panel className="log-panel"><div className="log-toolbar"><div><div className="eyebrow">ACTIVITY STREAM</div><h3>Structured event log</h3></div><Status tone="cyan">DEMO SESSION</Status></div>{['09:41:08.203  LOCAL_PERCEPTION  viewport captured','09:41:08.219  PII_DETECTOR      3 sensitive elements identified','09:41:08.220  PRIVACY_FIREWALL  2 elements redacted','09:41:08.224  DISCLOSURE         sanitized context prepared','09:41:08.601  CLOUD_REASONING    structured action received','09:41:08.607  ACTION_GUARD       click(continue) allowed'].map((x,i)=><div className="log-line" key={x}><span className="log-index">{String(i+1).padStart(2,'0')}</span><code>{x}</code><span className={i===5?'green-text':'muted'}>{i===5?'ALLOW':'INFO'}</span></div>)}</Panel> }
function Settings() { return <div className="settings-grid"><Panel><SectionTitle eyebrow="RUNTIME" title="Local engine" /><div className="setting-row"><div><strong>Inference backend</strong><span className="muted small">Local browser execution</span></div><Status>READY</Status></div><div className="setting-row"><div><strong>WebGPU</strong><span className="muted small">Hardware acceleration capability</span></div><Status tone="amber">NOT MEASURED</Status></div><div className="setting-row"><div><strong>Model state</strong><span className="muted small">No model metadata exposed</span></div><Status tone="amber">WAITING</Status></div></Panel><Panel><SectionTitle eyebrow="POLICY" title="Privacy boundary" /><div className="setting-row"><div><strong>Redaction policy</strong><span className="muted small">LG-PRIVACY-01</span></div><Status>ENFORCED</Status></div><div className="setting-row"><div><strong>Cloud disclosure</strong><span className="muted small">Minimum necessary context</span></div><Status tone="cyan">SANITIZED ONLY</Status></div><div className="setting-row"><div><strong>Raw screenshot upload</strong><span className="muted small">Disabled by architecture</span></div><Status tone="red">BLOCKED</Status></div></Panel></div> }
export default function Page() {
  const [page, setPage] = useState<PageKey>('Overview'); const [runState, setRunState] = useState<RunState>('idle'); const [mobileOpen, setMobileOpen] = useState(false)
  const runDemo = () => { if (runState === 'running') return; setRunState('running'); let i=0; const timer=setInterval(()=>{i++; if(i>=8){clearInterval(timer);setRunState('complete')}},420) }
  useEffect(()=>()=>{},[])
  return <main className="app-shell"><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark">LG</div><div><strong>LOCALGUARD</strong><span>PRIVACY CONTROL CENTER</span></div></div><div className="sidebar-status"><Status>LOCAL ENGINE READY</Status><span className="muted small">v0.1 · presentation build</span></div><nav>{nav.map(({label,icon:Icon})=><button key={label} className={page===label?'nav-item active':'nav-item'} onClick={()=>{setPage(label);setMobileOpen(false)}}><Icon size={16}/><span>{label}</span>{label==='Overview'&&<span className="nav-ping" />}</button>)}</nav><div className="sidebar-foot"><div className="boundary-mini"><ShieldCheck size={15}/><span><strong>Privacy boundary</strong><small>Raw screen stays local</small></span></div><span className="muted tiny">DESIGNED FOR INSPECTION</span></div></aside><div className="main-shell"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Toggle navigation"><Menu size={18}/></button><div className="breadcrumbs"><span>CONTROL CENTER</span><ChevronRight size={13}/><strong>{page.toUpperCase()}</strong></div><div className="top-actions"><span className="connection"><span className="pulse" /> browser connected</span><button className="icon-button" aria-label="Redo"><Redo2 size={16}/></button><div className="avatar">LG</div></div></header>{page==='Overview'?<Overview runState={runState} runDemo={runDemo}/>:<DataPage page={page}/>}</div></main>
}
